### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by surume**

### CODE REVIEW

**Comment by nownabe** [comment]
LGTM! :sparkles: 
It's so similar to my idea :heart_eyes:

**Comment by surume** [comment]
thanks a lot!! :sparkles: :sparkles: :sparkles:

**Comment by surume** [comment]
released v0.2.0!
https://rubygems.org/gems/itamae-plugin-recipe-anyenv/versions/0.2.0

**Comment by nownabe** [comment]
Thanks! :+1::sparkles::sparkles:

**Pull request merged**
